/// LIST PRODUCT
### 
GET http://localhost:8080/products?limit=10&page=2

/// GET PRODUCT BY ID
###
GET http://localhost:8080/products/5

/// CREATE PRODUCT
###
POST http://localhost:8080/products
Content-Type: application/json 

{
  "Name": "Product 12",
  "Description": "Nice to have, You should try this one",
  "Price": 190,
  "Image": "http://image.png"
}

/// EDIT PRODUCT
###
PUT http://localhost:8080/products/12
Content-Type: application/json 

{
  "Name":"Product 12",
  "Description":"Nice to have",
  "Price": 85666,
  "Image":"http://image.png"
}

/// DELETE PRODUCT
###
DELETE http://localhost:8080/products/12